# global settings
title: "GitHub and DoraemonYu"
description: "Hello:) I am DoraemonYu."
permalink: "/stories/:title"
url: https://doraemonyu.github.com
relative_permalinks: false
analytics_account: "UA-4907987-4"
show_resume: true

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "start.bat"]
markdown: kramdown
gems:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap

sass:
  style: :compressed

